#!/bin/bash
if [ $(id -u) -ne 0 ]; then
	clear
	echo -e "                      \033[1;31m[This script must be run as ROOT]\E[0m"
	echo ""
	else	

gnome-terminal --geometry=105x24 --hide-menubar -e ./src/rdp_brute.sh
fi 
exit 1;



