#!/bin/bash
ver=$(cat src/rdp_brute.sh | awk -F'=' '/ver=/ {print $2}' 2> /dev/null)
clear

if [[ $(id -u) -ne 0 ]]
	then
	clear
	echo -e "                      \033[1;31m[This script must be run as ROOT]\E[0m"
	echo ""
	else	

depend=$(dpkg -s curl  | grep 'Status' | awk -F':' '/Status: / {print $2}')
	if [ "$depend" = " install ok installed" ]; then
		clear 
			
			else
			echo -e "$aquamarine"
		while true; do
		echo    "Требующийся пакет Curl не установлен. Установить?"
                read -p "The required package Curl is not installed Install?[Y][N]" yn
			case $yn in
			[Yy]* ) apt-get update -y && apt-get dist-upgrade -y; apt install curl -y; break;;
			[Nn]* ) exit;;
			* ) echo "Enter answer [Y] or [N] ";;
		esac
	done
fi
clear
echo "Checking for updates..."

	TESTINTERNETCONNECTION=$(curl -s ident.me)
	if [[ "$TESTINTERNETCONNECTION" != "" ]]
	then
		updated=$(timeout -s SIGTERM 20 curl -s "https://raw.githubusercontent.com/getdrive/Lazy-RDP/master/src/rdp_brute.sh" | awk -F'=' '/ver=/ {print $2}' 2> /dev/null)
		if [[ "$ver" != "$updated" ]]
		then
			clear
			echo  "There is an update available."
			echo  "Current version: $ver"
			echo  "New version: $updated"

while true; do
		read -p "Update? [Y][N]" yn
			case $yn in
			[Yy]* ) wget -O src/rdp_brute.sh https://raw.githubusercontent.com/getdrive/Lazy-RDP/master/src/rdp_brute.sh && wget -O start https://raw.githubusercontent.com/getdrive/Lazy-RDP/master/start && clear; break;;
			[Nn]* ) clear;break;;
			* ) echo "Enter answer [Y] or [N] ";;
		esac
	done
		fi
else
echo "It seems there is no internet connection "
	 exit;
fi

sudo gnome-terminal --geometry=105x24+200+200 --hide-menubar -e ./src/rdp_brute.sh 2> /dev/null
fi 
exit 1;



